#/etc/netplan/99_config.yaml
#netplan configuration file 1 for Ubuntu Server 2: internet, dns, dhcp
network:
        version: 2
        renderer: networkd
        ethernets:
                #internet via host
                ens33:
                        #dhcp route adds default
                        dhcp4: true
                        dhcp4-overrides:
                                use-dns: false
                        nameservers:
                                addresses: [192.168.50.1]
                                search: [MHI]
                #dns
                ens38:
                        #static routes, do not add gateway4 or gateway6 so that netplan does not add default route                
                        dhcp4: no
                        addresses: [192.168.25.10/24]
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [nwsecdocker.jhu.edu]
                #dhcp
                ens39:
                        #static routes, do not add gateway4 or gateway6 so that netplan does not add default route                
                        dhcp4: no
                        addresses: [192.168.25.5/24]
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [nwsecdocker.jhu.edu]
