#/etc/netplan/100-config.yaml
#netplan configuration file 2 for UbuntuServerX86-64-infrastructure VM: suricata, auth, etc.
network:
        version: 2
        renderer: networkd
        ethernets:
                #container3
                ens40:
                        #dhcp route adds default
                        dhcp4: true
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [netsec-docker.isi.jhu.edu]
                #container4
                ens41:
                        #dhcp route adds default
                        dhcp4: true
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [netsec-docker.isi.jhu.edu]
                #container5
                ens42:
                        #dhcp route adds default
                        dhcp4: true
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [netsec-docker.isi.jhu.edu]
