#/etc/netplan/100_config.yaml
#netplan configuration file 2 for Ubuntu Server 2: suricata, auth, proxy, etc.
network:
        version: 2
        renderer: networkd
        ethernets:
                #suricata
                ens40:
                        #dhcp route adds default
                        dhcp4: true
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [nwsecdocker.jhu.edu]
                #auth
                ens41:
                        #dhcp route adds default
                        dhcp4: true
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [nwsecdocker.jhu.edu]
                #proxy
                ens42:
                        #dhcp route adds default
                        dhcp4: true
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [nwsecdocker.jhu.edu]

